version: '3.8'

services:
  postgresql-container:
    image: postgres
    container_name: postgresql-container
    environment:
      POSTGRES_PASSWORD: 2024pass
      POSTGRES_DB: zendy_whatsapp_db
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - wpp-net
  zendy-whatsapp:
    container_name: zendy-whatsapp
    build:
      context: .
      dockerfile: ./Dockerfile
    image: zendy-whatsapp:latest  # Define explicitamente o nome da imagem
    volumes:
      - '.:/app'
      - /app/node_modules
      - prisma:/prisma
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgres://postgres:2024pass@postgresql-container:5432/zendy_whatsapp_db
    depends_on:
      - postgresql-container
    networks: 
      - wpp-net

volumes:
  postgres_data:
  prisma:
networks:
  wpp-net:
    driver: bridge