name: Deploy to GCP

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgres://postgres:2024pass@postgresql-container:5432/zendy_whatsapp_db" > .env
          cat .env  # Depuração
          chmod 644 .env

      - name: Build Docker image with docker compose
        run: |
          docker compose build

      - name: Save Docker image to tar
        run: |
          docker save -o zendy-whatsapp.tar zendy-whatsapp:latest
          chmod 644 ./zendy-whatsapp.tar

      - name: Copy Docker image, .env, and docker-compose.yml to GCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          source: "zendy-whatsapp.tar,.env,docker-compose.yml,Dockerfile"
          target: "/tmp"

      - name: Deploy and restart application on GCP with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          script: |
            # Carrega a imagem Docker
            docker load -i /tmp/zendy-whatsapp.tar
            
            # Para e remove serviços existentes do Compose
            docker compose -f /tmp/docker-compose.yml down || true
            
            # Executa as migrações
            docker run --rm --env-file /tmp/.env zendy-whatsapp:latest npx prisma migrate deploy
            
            # Sobe o serviço com Docker Compose
            docker compose -f /tmp/docker-compose.yml up -d --build
            
            # Remove arquivos temporários
            rm /tmp/zendy-whatsapp.tar /tmp/.env /tmp/docker-compose.yml /tmp/Dockerfile