name: Deploy to GCP

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file
        run: |
          echo "DATABASE_URL=postgres://postgres:2024pass@postgresql-container:5432/zendy_whatsapp_db" > .env
          chmod 644 .env

      - name: Build Docker image with docker compose
        run: |
          docker compose build

      - name: Pull Postgres image
        run: |
          docker pull postgres:latest  # Puxa a imagem oficial do Postgres

      - name: Save Docker images to tar
        run: |
          docker save -o zendy-whatsapp.tar zendy-whatsapp:latest
          docker save -o postgresql-container.tar postgres:latest
          chmod 644 ./zendy-whatsapp.tar
          chmod 644 ./postgresql-container.tar

      - name: Copy Docker image, .env, and docker-compose.yml to GCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          source: "zendy-whatsapp.tar, postgresql-container.tar,.env,docker-compose.yml,Dockerfile,package.json,package-lock.json,prisma/"
          target: "/tmp/zendy-whatsapp-deploy"

      - name: Deploy and restart application on GCP with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          script: |
            # Cria e entra no diretório de deploy
            mkdir -p /tmp/zendy-whatsapp-deploy
            cd /tmp/zendy-whatsapp-deploy

            # Carrega a imagem Docker
            docker load -i /tmp/zendy-whatsapp-deploy/zendy-whatsapp.tar
            docker load -i /tmp/zendy-whatsapp-deploy/postgresql-container.tar
            
            # Para e remove serviços existentes do Compose
            docker compose -f /tmp/zendy-whatsapp-deploy/docker-compose.yml down || true
            
            # Executa as migrações
            # docker run --rm --env-file /tmp/zendy-whatsapp-deploy/.env zendy-whatsapp:latest npx prisma migrate deploy
            
            # Sobe o serviço com Docker Compose
            docker compose -f /tmp/zendy-whatsapp-deploy/docker-compose.yml up -d --build

            # Sobe os serviços com Docker Compose
            # docker compose -f docker-compose.yml up -d --build
            
            # Executa as migrações após os serviços estarem rodando
            docker compose -f docker-compose.yml exec -T zendy-whatsapp npx prisma migrate deploy
            
            # Remove arquivos temporários
            rm -rf /tmp/zendy-whatsapp-deploy